- CONTRIBUTING.md
Solve issue #46 
Everything ok!
> Add contributing how-to

- Dockerfile
- docker-entrypoint.sh
- jobs/settings/base.py
- jobs/settings/development.py
- jobs/settings/local.py
With this commit I introduce a Dockerfile and additional settings to containerize the application. #3 
Scope:
Containerizing the application will require futher discussion to clarify:
- how we want to manage settings override for different environments
- how to replace sqllite with a Database container and docker-compose
- context for additional environments to deploy the application
Known Issues:
- containers uses a sqllite file as a database and with the current structure cannot be externalized with a docker volume
- missing documentation on how to build and use the docker image (will include after the introduction of the docker-compose)
- dockerfile does not include options to be used for app development
> feat: App containerization: dockerfile and settings

- .github/workflows/pythonapp.yml
- checks.py
- requirements-test.txt
Close #52
Add a 'checks.py' standalone script in order to implement custom typing tests (find and filter files, then run the tests on those files).
**Observation:**
We can extend this script to execute the other tests on the code as well like black/lint.
We can also run the pytest scripts from it, so it can act as a command handler for the tests.
> Implement typing test

- jobsapp/urls.py
- jobsapp/views/employer.py
- templates/jobs/delete.html
- templates/jobs/employer/dashboard.html
refs #33
Add delete view on employer dashboard
Done
> Add delete view on employer dashboard

- jobs/settings/__init__.py
refs #31 
Added django-constance plugin to the project and a sample configuration to show how to use it.
> Add Django-constance

- requirements.txt
> Add django-constance to requirements.txt

- .github/workflows/pythonapp.yml
It ensures that our CI action will be triggered also on each PR.
Action name is renamed to `code-check` to be more understandable
Fix #78
Before create your PR, please make sure your code is formatted running:
```bash
$ >> black --exclude=venv,__pycache__ ./
```
> Dispatch GH action on each PR

- .github/pull_request_template.md
- CONTRIBUTING.md
refs #85
Please provide enough information so that others can review your pull request:
Improves documentation about, "how to use `pre-commit`" locally. Also informs that users with permission can create PR directly against this repository.
> Minor documentation improvement

- accounts/admin.py
- jobsapp/admin.py
PR related with Issue #24 providing a first version of current models in admin site.
done
> First approach to get models in adminsite

- .env.dev.sample
- jobs/settings.py
- requirements.txt
- tests/pytest.ini
Sentry setup 
FIX: https://github.com/GeeksCAT/anem-per-feina/issues/109
We need to define the environment variable in production with the right SENTRY_URL
> Sentry setup

- .gitignore
- docker-compose.yml
- jobs/celery.py
- jobs/settings.py
- jobsapp/models.py
- notifications/README.md
- notifications/apps.py
- notifications/decorators.py
- notifications/events.py
- notifications/providers/__init__.py
- notifications/providers/base.py
- notifications/providers/telegram.py
- notifications/providers/twitter.py
- notifications/settings.py
- notifications/tasks.py
- notifications/templates/notifications/telegram_new_job.html
- notifications/templates/notifications/twitter_new_job.html
- requirements.txt
- tasks.py
- tests/conftest.py
This PR implement the notification's system described at:
fixed #8 
```bash
```
> (#8) [New]: Notification system

- jobs/settings.py
- jobs/urls.py
- jobsapp/admin.py
- jobsapp/api/urls.py
- jobsapp/api/views/common.py
- jobsapp/templates/base.html
- templates/flatpages/about-us.html
- tests/jobsapp/test_endpoints.py
Please describe your pull request. If it fixes a bug or resolves a feature request, be sure to link to that issue. When linking to an issue, please use `refs #...` in the description of the pull request.
Partial solves issue #22 
Adds endpoint:
`/api/about-us`
Adds url (html page):
`/about-us`
> Add About us page

- jobs/settings.py
- jobsapp/forms.py
- jobsapp/templates/base.html
- jobsapp/templates/contact_us.html
- jobsapp/urls.py
- jobsapp/views/home.py
Please describe your pull request. If it fixes a bug or resolves a feature request, be sure to link to that issue. When linking to an issue, please use `refs #...` in the description of the pull request.
Partial solves issue #22
Adds contact form frontend view url:
`/contact-us`
> Add "contact us" form to front-end page

- jobsapp/api/views/users.py
Fix django.db.utils.ProgrammingError
> Fix database relation error

- jobs/settings.py
- jobsapp/templates/base.html
- requirements.txt
Show cookie law banner.
fixes #21 
```bash
```
> (#21) [New]: Cookie law

- jobsapp/forms.py
- jobsapp/locale/ca/LC_MESSAGES/django.po
- jobsapp/locale/es/LC_MESSAGES/django.po
- jobsapp/templates/contact_us.html
Language hidden input field added in contact form for formspree.
```bash
```
> Language added to contact form for formspree

- jobsapp/managers.py
- jobsapp/models.py
- jobsapp/views/home.py
Only show unfilled jobs at home
```bash
```
> Only show unfilled jobs at home

- jobsapp/forms.py
- jobsapp/templates/jobsapp/create.html
- jobsapp/views/employer.py
* Security fixes, like any user could delete another user's job.
* Permissions added in update, delete and filled views
* Order added in jobs list showed in dashboard
```bash
```
> Security fixes, permissions and other improvements

- jobs/settings.py
It sorts languages to be:
- ca
- es
- en
> Sort languages (ca, es, en)

- jobsapp/templates/home.html
Please describe your pull request. If it fixes a bug or resolves a feature request, be sure to link to that issue. When linking to an issue, please use `refs #...` in the description of the pull request.
Please provide enough information so that others can review your pull request:
Explain the details for making this change. What existing problem does the pull request solve?
```bash
```
> Fix image link to offer

- accounts/api/serializers.py
- accounts/api/views.py
- accounts/forms.py
- accounts/models.py
- accounts/views.py
- jobsapp/api/serializers.py
- jobsapp/api/views/jobs.py
- jobsapp/fields.py
- jobsapp/models.py
- jobsapp/views/employee.py
- jobsapp/views/employer.py
- tests/conftest.py
- tests/jobsapp/test_endpoints.py
This PR is only a small code refactor of some of my previous contributions making the code more idiomatic django/django rest. Also I switched `ugettext()` (which is deprecated) by `gettext()`, that removes some django deprecated warnings when running pytest.
Related to #149
> Code refactoring
